version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_DEFAULT_CONF}
      - ./logs/nginx:/var/log/nginx
      - ${NGINX_SSL_CERT}
      - ${NGINX_SSL_KEY}
    restart: always

  jenkins-slave-fortran:
    build: jenkins-slave-fortran
    container_name: fortran-slave
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    expose:
        - "22"
    restart: unless-stopped
